version: '3.8'

services:
  app:
    container_name: app-auction
    restart: always
    build: .
    environment:
     - PORT=3000
     - NODE_ENV=development
    ports:
     - "3000:3000"
    volumes:
     - .:/usr/src/app
    command: sh -c "npm install && npm run start:dev"




  db:
    container_name: postgres-auction
    restart: always
    image: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: lucas
      POSTGRES_DB: auction
    ports:
      - "5432:5432"

volumes:
  pgdata:
